# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1024bbb1090d720ffe915d8bfda68dd7f23682d30be35adafb3a3c4b3ae94afe3019b471b94453c7a7022d4e2f49eca3e124a27623df27df160a10306eccb566

test:
  secret_key_base: 74be72f155878284876cdce221ad9a37496a4dcf3034bd66dc087a41ef997b762ee3be269c2632bc643ff884d20bbaef177437e41c19ee45e3e665184a90b7b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
